# Generated by Django 5.2 on 2025-04-25 08:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jornada',
            options={'ordering': ['-fecha', 'trabajador'], 'verbose_name_plural': 'Jornadas'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Locales'},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-fecha', 'estado'], 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='jornada',
            name='horas_extras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='jornada',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='local',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 25, 8, 47, 52, 911391, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='necesita_cambio_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='asignado_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('trabajador', 'Trabajador'), ('admin_local', 'Administrador del Local'), ('admin_sistema', 'Administrador del Sistema')], default='trabajador', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='jornada',
            unique_together={('trabajador', 'fecha')},
        ),
    ]
